package org.xlbean.xljson;

import org.xlbean.xljson.builder.XlJsonBuilder;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class XlJsonMain {

    public static void main(String[] args) {
        // new XlJsonParser().run();

        new XlJsonBuilder().build();
    }

}
